import {
  createAsyncThunk,
  createSlice,
  PayloadAction,
  createSelector,
} from "@reduxjs/toolkit";
import { RootState } from "../../app/store";
import ReposManager from "./reposManager";

export interface Repo {
  fullName: string;
  url: string;
  description: string;
  stars: number;
  isStarred: boolean;
  id: number;
}

export interface RepoFilters {
  sort: "stars" | string;
  order: "asc" | "desc";
}

interface LocalRepoFilters {
  starred: boolean;
}

export interface ReposState {
  data: Repo[];
  loading: boolean;
  error?: string;
  filters: RepoFilters;
  localFilters: LocalRepoFilters;
}

const initialState: ReposState = {
  data: [],
  loading: false,
  filters: {
    sort: "stars",
    order: "desc",
  },
  localFilters: {
    starred: false,
  },
};

export const getTrendingReposAsync = createAsyncThunk(
  "repos/getAllRepos",
  async (arg, { getState }) => {
    const state = getState() as RootState;
    const response = await ReposManager.getTrendingRepos(state.repos.filters);
    return response;
  }
);

export const reposSlice = createSlice({
  name: "repos",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    starRepo: (state, action: PayloadAction<number>) => {
      const index = action.payload;
      const repo = state.data[index];
      repo.isStarred = true;
      repo.stars += 1;
      localStorage.setItem(repo.id.toString(), "1");
    },
    unStarRepo: (state, action: PayloadAction<number>) => {
      const index = action.payload;
      const repo = state.data[index];
      repo.isStarred = false;
      repo.stars -= 1;
      localStorage.removeItem(repo.id.toString());
    },
    setStarredFilter: (state, action: PayloadAction<boolean>) => {
      state.localFilters.starred = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getTrendingReposAsync.pending, (state) => {
        state.loading = true;
      })
      .addCase(
        getTrendingReposAsync.fulfilled,
        (state, action: PayloadAction<Repo[]>) => {
          state.loading = false;
          state.data = action.payload;
        }
      );
  },
});

export const { starRepo, unStarRepo, setStarredFilter } = reposSlice.actions;

export const selectRepos = (state: RootState) => state.repos.data;

export const selectStarredRepos = createSelector([selectRepos], (repos) =>
  repos.filter((repos) => repos.isStarred)
);
export const selectLocalFilters = (state: RootState) =>
  state.repos.localFilters;

export const selectComputedRepos = createSelector(
  [selectLocalFilters, selectRepos, selectStarredRepos],
  (localFilters, repos, starredRepos) =>
    localFilters.starred ? starredRepos : repos
);
export default reposSlice.reducer;
